language: python
python:
- 3.6
before_install:
- python --version
- pip install -r requirements.txt
script:
- pylint_runner
- pytest --cov=com.ac5 com/ac5/test/
<<<<<<< HEAD

=======
>>>>>>> 82ac80120ba9b0c695f39384a902993d6fe3e96e
